-- 직책코드
INSERT INTO DUTY (DUTY_CD, DUTY_NM) VALUES (SEQ_DUTY.NEXTVAL, '팀원');
INSERT INTO DUTY (DUTY_CD, DUTY_NM) VALUES (SEQ_DUTY.NEXTVAL, '팀장');
INSERT INTO DUTY (DUTY_CD, DUTY_NM) VALUES (SEQ_DUTY.NEXTVAL, '실장');
INSERT INTO DUTY (DUTY_CD, DUTY_NM) VALUES (SEQ_DUTY.NEXTVAL, '본부장');

UPDATE DUTY SET DUTY_PARENT_CD = 2 WHERE DUTY_CD = 1;
UPDATE DUTY SET DUTY_PARENT_CD = 3 WHERE DUTY_CD = 2;
UPDATE DUTY SET DUTY_PARENT_CD = 4 WHERE DUTY_CD = 3;

-- 코드
INSERT INTO EMP (EMP_ID, EMP_NM) VALUES (SEQ_EMP.NEXTVAL, '신승범');
INSERT INTO EMP (EMP_ID, EMP_NM) VALUES (SEQ_EMP.NEXTVAL, '한석원');
INSERT INTO EMP (EMP_ID, EMP_NM) VALUES (SEQ_EMP.NEXTVAL, '현우진');

