-- employee
CREATE TABLE EMP
(
    EMP_ID      LONG            NOT NULL,
    EMP_NM      VARCHAR(255)    NOT NULL
);

ALTER TABLE EMP ADD CONSTRAINT PK_EMP PRIMARY KEY (EMP_ID);

CREATE SEQUENCE SEQ_EMP
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 99999999;

-- current emp dispatch
CREATE TABLE CURRENT_EMP_DISPATCH
(
    EMP_ID              LONG            NOT NULL,
    EMP_DISPATCH_ID     VARCHAR(255)    NOT NULL
);

ALTER TABLE CURRENT_EMP_DISPATCH ADD CONSTRAINT PK_CURRENT_EMP_DISPATCH PRIMARY KEY (EMP_ID);

-- duty
CREATE TABLE DUTY
(
    DUTY_CD         LONG            NOT NULL,
    DUTY_NM         VARCHAR(255)    NOT NULL,
    DUTY_PARENT_CD  LONG            NULL
);

ALTER TABLE DUTY ADD CONSTRAINT PK_DUTY PRIMARY KEY (DUTY_CD);

CREATE SEQUENCE SEQ_DUTY
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 99999999;

-- dispatch
CREATE TABLE DISPATCH
(
    DISPATCH_ID         LONG            NOT NULL,
    DISPATCH_TITLE      VARCHAR(255)    NOT NULL,
    DISPATCH_STDT       TIMESTAMP(6)    NULL,
    APPROVAL_STATUS_CD  LONG            NOT NULL
);

ALTER TABLE DISPATCH ADD CONSTRAINT PK_DISPATCH PRIMARY KEY (DISPATCH_ID);

COMMENT ON COLUMN DISPATCH.APPROVAL_STATUS_CD IS '0(상신대기), 1(결재대기), 2(결재완료)';
ALTER TABLE DISPATCH ADD CONSTRAINT CK_DISPATCH_1 CHECK (APPROVAL_STATUS_CD <= 3 AND APPROVAL_STATUS_CD >= 0);

CREATE SEQUENCE SEQ_DISPATCH
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 99999999;

-- emp dispatch
CREATE TABLE EMP_DISPATCH
(
    EMP_DISPATCH_ID     LONG            NOT NULL,
    DISPATCH_ID         LONG            NOT NULL,
    EMP_ID              LONG            NOT NULL,
    DUTY_CD             LONG            NOT NULL,
    DISPATCH_EDDT       TIMESTAMP(6)    NOT NULL,
    MULTIJOB_CD         LONG            NOT NULL,
    DISPATCH_TYPE_CD    LONG            NOT NULL
);

ALTER TABLE EMP_DISPATCH ADD CONSTRAINT PK_EMP_DISPATCH PRIMARY KEY (EMP_DISPATCH_ID);

COMMENT ON COLUMN EMP_DISPATCH.MULTIJOB_CD IS '0(주), 1(겸직), 2(겸직해제)';
ALTER TABLE EMP_DISPATCH ADD CONSTRAINT CK_EMP_DISPATCH_1 CHECK (MULTIJOB_CD <= 3 AND MULTIJOB_CD >= 0);

COMMENT ON COLUMN EMP_DISPATCH.DISPATCH_TYPE_CD IS '공통코드';

CREATE SEQUENCE SEQ_EMP_DISPATCH
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 99999999;


-- Foreign key
-- cascade on emp delete, set null on others
ALTER TABLE DUTY ADD CONSTRAINT FK_DUTY_1 FOREIGN KEY (DUTY_PARENT_CD)
    REFERENCES DUTY(DUTY_CD) ON DELETE SET NULL;

ALTER TABLE CURRENT_EMP_DISPATCH ADD CONSTRAINT FK_CURRENT_EMP_DISPATCH_1 FOREIGN KEY (EMP_ID)
    REFERENCES EMP(EMP_ID) ON DELETE CASCADE;

ALTER TABLE CURRENT_EMP_DISPATCH ADD CONSTRAINT FK_CURRENT_EMP_DISPATCH_2 FOREIGN KEY (EMP_DISPATCH_ID)
    REFERENCES EMP_DISPATCH(EMP_DISPATCH_ID) ON DELETE SET NULL;

ALTER TABLE EMP_DISPATCH ADD CONSTRAINT FK_EMP_DISPATCH_1 FOREIGN KEY (DISPATCH_ID)
    REFERENCES DISPATCH(DISPATCH_ID) ON DELETE CASCADE;

ALTER TABLE EMP_DISPATCH ADD CONSTRAINT FK_EMP_DISPATCH_2 FOREIGN KEY (EMP_ID)
    REFERENCES EMP(EMP_ID) ON DELETE CASCADE;

ALTER TABLE EMP_DISPATCH ADD CONSTRAINT FK_EMP_DISPATCH_3 FOREIGN KEY (DUTY_CD)
    REFERENCES DUTY(DUTY_CD) ON DELETE SET NULL;

-- view

-- function
